name: Publish to app service

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level' 
        required: true
        default: 'warning'
      tags:
        description: 'Manual test/deploy' 

jobs:
    

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Delete Relatude.setup
      run: rm ExploreNorway/Relatude.setup
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ExploreNorway/ExploreNorway.csproj -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: ExploreNorway/website/**
        if-no-files-found: error
    
    
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: website
        path: website
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.5
      with:
        # Name of the Azure Web App
        app-name: 'ExploreNorwayCore'
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}

    - name: Azure logout
      run: |
        az logout
